### ISSUE TITLE
Failed to restore checkpoint. Help!

### ISSUE THREAD

**Issue by Girum** [exelban/myo-armband-nn#1]
Hi! I'm using your solution. I ran the train, and when I run the predict with dataset, it was ok. But when I run the predict (from Myo), it recognizes the archive from checkpoint but failures to restore it. Well... the archive is the same hehe... How can I proceed?

**Comment by exelban** [comment]
@Girum can you post the output error?

**Comment by Girum** [comment]
Sorry. I found the error. The predict not defined how much classes has the model. I just use model(6) and the program run!

Thanks!
