### ISSUE TITLE
data raw 

### ISSUE THREAD

**Issue by willy90806k** [exelban/myo-armband-nn#3]
Why you can have 64 features to use? 
Myo just have 8 feature , doesn't it?

**Comment by exelban** [comment]
You have 8 sensors, and each sensor return 8 values.

**Comment by willy90806k** [comment]
Can i ask you how to take 64 value by your method?
I'm a myo's novice.
I think mine just a mistake.

**Comment by exelban** [comment]
@willy90806k just make one dimension array from your output data.
And don't forget to remove date value.

**Comment by willy90806k** [comment]
I just only can take 8 value out in my EMG extractor.
Is it using  the EMG data only ?
Or also have another.

If you have  some examples to me , i will  be grateful.

**Comment by exelban** [comment]
@willy90806k post output

**Comment by willy90806k** [comment]
@exelban
I post my extractor at Google Driver ,you can try it. 
It will put your output values at [\8channelChart\8channelChart \ .txt] .

https://drive.google.com/file/d/1PQp0uiMvHocPObLMQ2ameY7_DtZigYvI/view?usp=sharing

0	6	-4	-2	7	29	34	-1	
0	-15	-3	-5	4	-49	-22	0	
1	2	-4	-1	-12	40	-6	-1	
-1	3	1	0	-5	16	19	-1	
-2	-3	-1	-3	0	-85	-18	1	
-2	-7	-1	3	4	102	2	-1	

It look like this , and I change it to the csv in tensorflow then change it to npx .

**Comment by exelban** [comment]
@willy90806k ok, sorry.
I just get 8 times value from sensor for some unification.
So, 64 array its just collected 8 times EMG data from myo-armband.

I have armband only for few days for tests, and forgot about this.
I will try to get armband for few days and post code for collecting data.

**Comment by willy90806k** [comment]
Please don't say sorry . I'm grateful you can answer .  :))
[
def model(_NUM_CLASSES = 4):

    with tf.name_scope('data'):
        x = tf.placeholder(tf.float32, shape=[None, 64], name='Input')
        y = tf.placeholder(tf.float32, shape=[None, _NUM_CLASSES], name='Output')

    # Store layers weight & bias
    weights = {
        'h1': tf.Variable(tf.random_normal([64, 528])),
        'h2': tf.Variable(tf.random_normal([528, 786])),
        'h3': tf.Variable(tf.random_normal([786, 1248])),
        'out': tf.Variable(tf.random_normal([1248, _NUM_CLASSES]))
]
So , if I change 64 to 8 ,should i change  weight's number or  _NUM_CLASSES ?

**Comment by exelban** [comment]
@willy90806k nope. You need to change all numbers of neurones.
